algoritmo "desafio01"
// Função : Desafio sobre o que foi estudado
// Autor :  Thomaz Victor

var
   msg    : caractere
inicio
      escreval  ("|=======================|", msg)
      escreval  ("| CURSO DE ALGORITMOS   |", msg)
      escreval  ("| Professor Edson       |", msg)
      escreval  ("|=======================|", msg)

// Exercício sobre o que foi estudado no Curso de Algoritmo do Professor Edson Maia no YT

fimalgoritmo
